In [24]:
import numpy as np

# Creating a NumPy array with a single element
b = np.array(44)

# Creating a NumPy array from a list
l = [1, 2, 3, 4, 6, 6, 8]
a = np.array(l)

# Creating a 2D NumPy array from a list of lists
l1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a2 = np.array(l1)

# Printing the dimensions of the arrays
print(b.ndim)  # Expected output: 0
print(a.ndim)  # Expected output: 1
print(a2.ndim) # Expected output: 2

# Printing the shape of the 2D array
print(a2.shape) # Expected output: (3, 3)
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create a slice of the array
sarr = arr[1:5]

# Print the original array
print("Original array:", arr)

# Print the sliced array
print("Sliced array:", sarr)

# Modify an element in the sliced array
sarr[2] = 100

# Print the arrays after modification
print("Modified original array:", arr)
print("Modified sliced array:", sarr)


0
1
2
(3, 3)


The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [25]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


numpy.zeros() in Python
The numpy.zeros() function is one of the most significant functions which is used in machine learning programs widely. This function is used to generate an array containing zeros.
The numpy.zeros() function provide a new array of given shape and type, which is filled with zeros.

In [27]:
import numpy as np

# Create a 2-D array of zeros with shape (3, 4)
arr = np.zeros((3, 4))

print("2-D array of zeros:")
print(arr)


2-D array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


The numpy.ones function in NumPy is used to create an array of a specified shape filled with ones. Here are some examples of how to use numpy.ones

In [26]:
import numpy as np

# Create a 2-D array of ones with shape (3, 4)
arr = np.ones((3, 4))

print("2-D array of ones:")
print(arr)


2-D array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


The eye tool returns a 2-D array with 1's as the diagonal and @'s elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k. A positive k is for the upper diagonal, a negative k is for the lower, and a 0k (default) is for the main diagonal.

In [28]:
import numpy as np

# Create a 4x4 matrix with ones on the diagonal above the main diagonal
eye_matrix_offset = np.eye(4, k=1)

print("4x4 Matrix with ones on the diagonal above the main diagonal:")
print(eye_matrix_offset)


4x4 Matrix with ones on the diagonal above the main diagonal:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


arr6=

In [29]:
arr6=np.diag([1,2,3,4,5])
print(arr6)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


randint() is an inbuilt function of the randon module in Python3. The random module gives access to various useful functions one of them being able to generate random numbers, which is randint()


In [1]:
import numpy as np

# Generate a 1D array of 4 random numbers
rand_1d = np.random.rand(4)
print(rand_1d)

# Generate a 2D array of shape (2, 3) with random numbers
rand_2d = np.random.rand(2, 3)
print(rand_2d)


[0.60537139 0.71552727 0.31346437 0.83911265]
[[0.48511106 0.67827927 0.14892303]
 [0.77568014 0.25914504 0.91176729]]


reshape()

In [2]:
import numpy as np

# Create a 1D array of 12 elements
arr = np.arange(12)
print("Original array:")
print(arr)

# Reshape the array to 3x4
reshaped_arr = arr.reshape(3, 4)
print("\nReshaped array to 3x4:")
print(reshaped_arr)

# Reshape the array to 4x3
reshaped_arr2 = arr.reshape(4, 3)
print("\nReshaped array to 4x3:")
print(reshaped_arr2)

# Reshape the array to 2x2x3
reshaped_arr3 = arr.reshape(2, 2, 3)
print("\nReshaped array to 2x2x3:")
print(reshaped_arr3)


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped array to 4x3:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Reshaped array to 2x2x3:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


seed()

In [10]:
import numpy as np

# Set the seed for reproducibility
np.random.seed(111)

# Generate an array of 30 random integers between 1 and 500 and reshape it to 6x5
ar = np.random.randint(1, 500, 30).reshape(6, 5)
print("Original array:")
print(ar)

# Slice and print the subarray from the 3rd row and 3rd column onwards
print("\nSubarray from the 3rd row and 3rd column onwards:")
print(ar[2:, 2:])

# Slice and print the subarray from the 4th to 5th rows and 3rd to 4th columns
print("\nSubarray from the 4th to 5th rows and 3rd to 4th columns:")
print(ar[3:5, 2:4])


[[341 365 469 213  87]
 [276 170 323 119 467]
 [297 456 442   8 269]
 [267 450 369 217 285]
 [271 419  22  55 201]
 [ 38 461 231 187 269]]
[[442   8 269]
 [369 217 285]
 [ 22  55 201]
 [231 187 269]]
[[369 217]
 [ 22  55]]


In [14]:
import numpy as np
ar=np.arange(1,15)
print(ar)
print(ar[ar%2==0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]


More array functions

In [ ]:
import numpy as np

# Define the array
ar = np.array([1, 20, 5, 9, 3, 4, 8, 5, 6, 2, 25, 2, 22, 65, 3, 33])

# Find and print the minimum value in the array
print("Minimum value in the array:", np.min(ar))

# Find and print the maximum value in the array
print("Maximum value in the array:", np.max(ar))

# Find and print the index of the minimum value in the array
print("Index of the minimum value in the array:", np.argmin(ar))

# Find and print the index of the maximum value in the array
print("Index of the maximum value in the array:", np.argmax(ar))

# Compute and print the square root of each element in the array
print("Square root of each element in the array:\n", np.sqrt(ar))

# Compute and print the sine of each element in the array
print("Sine of each element in the array:\n", np.sin(ar))

# Compute and print the cosine of each element in the array
print("Cosine of each element in the array:\n", np.cos(ar))